name: simple_calendar_app
description: A new Flutter application.

publish_to: 'none'
version: 1.0.15+16

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: 2.2.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  simple_logger: ^1.8.1
  freezed_annotation: ^0.14.2
  provider: ^5.0.0
  rxdart: ^0.27.1
  json_serializable: ^4.1.3
  fluttertoast: ^8.0.7
  uuid: ^3.0.4
  package_info: ^2.0.2
  in_app_review: ^2.0.2
  url_launcher: ^6.0.3
  fluentui_system_icons: ^1.1.134
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.6
  get_it: ^7.2.0
  tuple: ^2.0.0
  animations: ^2.0.1
  equatable: ^2.0.3
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  firebase_crashlytics: ^2.1.1
  sembast: ^3.1.0+2
  built_collection: ^5.1.0
  flutter_native_timezone: ^2.0.0
  timezone: ^0.7.0
  permission_handler: ^8.1.3
  modal_bottom_sheet: ^2.0.0
  implicitly_animated_reorderable_list: ^0.4.0
  focus_detector: ^2.0.0
  numberpicker: ^2.1.1
  user_messaging_platform: ^1.0.0
  collection: ^1.15.0
  google_sign_in: ^5.0.5
  googleapis: ^4.0.0
  bouncing_widget: ^2.0.0
  flutter_local_notifications: ^6.0.0
  flutter_icons: ^1.1.0
  nifu_flutter_kit:
    git:
      url: git@github.com:aaazlkm/nifu-flutter-kit.git
      ref: v2.0.7
  simple_app_kit:
    git:
      url: git@github.com:aaazlkm/simple-app-kit.git
      ref: v3.0.9
  review_dialog:
    git:
      url: git@github.com:aaazlkm/review-dialog.git
      ref: v3.0.0
  result:
    git:
      url: git@github.com:aaazlkm/result.git
      ref: v2.0.1
  calendar_event:
    git:
      url: git@github.com:aaazlkm/calendar_event.git
      ref: v2.0.0
  device_calendar:
    git:
      url: git@github.com:builttoroam/device_calendar.git
      ref: 2a30101d3451fce0a179a5d45ef29e7445d6c31d

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  freezed: ^0.14.2
  flutter_launcher_icons: ^0.9.0
  flutter_gen: ^3.1.1
  dart_lint:
    git:
      url: git@github.com:aaazlkm/dart_lint.git
      ref: v2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/image/cat_sitting.png
    - assets/image/cat_bothering.png
    - assets/image/ic_launcher_license.png
    - assets/image/calendar.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/launcher-icon-512.png"
  # only available for Android 8.0 devices and above
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/launcher/adaptive-icon-324.png"

scripts:
  clean: flutter clean
  buildRunner: flutter pub run build_runner build
  buildRunnerDelete: flutter pub run build_runner build --delete-conflicting-outputs
  assetGen: fluttergen -c pubspec.yaml
  launcherIcon: flutter pub run flutter_launcher_icons:main
  developApk: flutter build apk --debug --dart-define=FLAVOR=develop --flavor development --no-sound-null-safety
  releaseApk: flutter build apk --release --dart-define=FLAVOR=production --flavor production --no-sound-null-safety
  developBundle: flutter build appbundle --debug --dart-define=FLAVOR=develop --flavor development --no-sound-null-safety
  releaseBundle: flutter build appbundle --release --dart-define=FLAVOR=production --flavor production --no-sound-null-safety
  releaseIos: flutter build ipa  --release --dart-define=FLAVOR=production --flavor production --no-sound-null-safety